import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header/Header';
import SearchBox from '../components/SearchBox/SearchBox';
import { useSession } from 'next-auth/react';

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  console.log(session?.accessToken, 'session');
  console.log(status, 'status');
  return (
    <div className="bg-black w-full h-screen flex flex-col">
      <Head>
        <title>List it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        <Header />
        <div className="m-auto mt-10 flex flex-col items-center gap-10">
          <h1 className="text-white text-3xl font-bold text-center">
            Find what you are looking for
          </h1>

          <SearchBox />
        </div>
      </main>
    </div>
  );
};

export default Home;
